services:
  lm-landing-back:
    build: .
    container_name: lm-landing-back
    ports:
      - "${PORT:-8092}:${PORT:-8092}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
